[AUD-73] 토스트 컴포넌트 기능 구현
Nexters/audy-client pull request #43
Opened 2024-02-21 09:01 UTC by KimGaeun0806

### 📃 변경사항  
- Toast 내용물을 저장하는 ToastProvider 생성
- Toast를 사용할 수 있는 useToast hook 구현
  - 아래와 같이 사용할 수 있음 
  ```ts
  const { setToast } = useToast();
  setToast( '토스트 냠뇸뇸^^' );
  ``` 
- Toast 공용 컴포넌트 생성

### 🫨 고민한 부분 
- Toast를 어떻게 구현할지
  - 어떤식으로 Toast와 useToast를 구현할지 고민을 꽤나 했습니다.
  - 전역을 최대한 안쓰는게 좋다고 생각했으나, 그럴 경우에는 Toast를 쓰는 곳마다 `<Toast />`를 호출할 수밖에 없다고 판단했습니다.
  - 사용상의 편의를 위해서 ToastProvider를 만들게 되었습니다.
  - 결과적으로는, 
    - Toast의 메시지를 전역으로 저장하고
    - Toast 메시지가 빈문자열이면 Toast 컴포넌트가 null을 반환하며
    - 빈문자열이 아닐 경우에는 3초 후 빈문자열이 되도록 했습니다.
    - 여기서 setTimeout을 쓰지 않고 onAnimationEnd를 사용하여 구현했습니다.

### 🎇 동작 화면 
https://github.com/Nexters/audy-client/assets/80266418/4cff9137-624a-47b0-a2af-09de12d6914c

### 💫 기타사항
- 디자인이 미완성된 관계로 기능만 따로 이슈 분리하였습니다.
- Toast 구현에 있어 더 좋은 방법이 있으면 코멘트 주세요!

2024-02-21 09:17 UTC, KimGaeun0806 commented
현재 토스트가 사라질 때 페이지가 리렌더링된다는 문제가 있어서 수정하면 좋을 것 같긴 합니다...

2024-02-22 13:26 UTC, RookieAND requested changes
빠르게 작업해주셔서 감사합니다 가은님.
다만 구조적으로 유지 보수가 어려울 것 같은 포인트가 있어 이에 대한 수정 및 제안을 요청합니다.

추가로 현재 토스트가 사라질 때 페이지가 리렌더링된다는 문제가 있는 크리티컬한 이슈인 것 같습니다.
아무래도 RouterProvider 단에서 state 변경으로 인한 리렌더 때문에 자식 컴포넌트 (페이지 전체) 도 렌더링이 될 수밖에 없겠죠..

이 부분은 굳이 Provider 를 전역으로 감싸지 않아도 해결할 수 있는 방법이 있는지 찾아보면 좋을 거 같습니다.

2024-02-22 13:26 UTC, RookieAND commented on src/utils/toast/ToastProvider.tsx
> +interface PropsType extends PropsWithChildren {}
별다른 Props 가 없으면 그냥 PropsWithChildren 으로 써도 괜찮을 거 같아요

2024-02-22 13:26 UTC, RookieAND commented on src/components/toast/Toast.css.ts
> +        zIndex: 1000,
이 부분도 Z-Index 를 사용할 때는 Foundation 레벨에서 정의하기로 협의했던 것 같습니다.

2024-02-22 13:26 UTC, RookieAND commented on src/components/toast/Toast.css.ts
> +const fadeOutAnimation = keyframes({
keyframe 을 사용해서 직접 제어하는 것도 좋지만 제안을 드리고 싶습니다.

저희가 framer-motion 을 적극적으로 활용하기로 한 만큼, 애니메이션의 경우에도 직접 제어하기보다 framer-motion 으로 대체하여 사용해보는 건 어떨까요?

2024-02-22 13:26 UTC, RookieAND commented on src/components/toast/Toast.tsx
> +    const { toastMessage, setToast } = useToast();
해당 토스트의 구조를 생각했을 때, 만약 사용자가 토스트 메세지를 트리거하는 요소와 짧은 시간 내에 여러 번 상호작용 한다고 생각해보겠습니다.

보통 토스트 메세지의 경우 이전 메세지가 종료된 이후에 다음 메세지를 보여주는 형식인데, 이렇게 되면 토스트 메세지가 끝나기도 전에 다음 메세지가 State 로 들어오기 때문에 렌더링이 발생하여 메세지 간의 애니메이션이 재생되지 않을 것 같아요.

해당 스펙을 고려하지 않아도 되는지 (먼저 들어온 메세지 대로 순차적으로 출력할 수 있도록 할지), 이 부분은 디자이너 분들과 이야기를 나눠야 할 듯 싶습니다.

2024-02-22 13:26 UTC, RookieAND commented on src/components/toast/Toast.tsx
> +    return (
`React.createPortal` 을 사용해서 화면 위에 놓을 수 있는 요소들은 별도의 Portal Root 에 놓고 제어를 하는 방식은 어떨까요?

이러한 컴포넌트들이 Toast, SnackBar, Modal 인데 각각의 컴포넌트들에 대한 Provider 를 Router 단에서 계속 감싸게 되면 구조적으로 상당히 좋지 않은 모습이 될 것 같아요.

2024-02-24 15:46 UTC, KimGaeun0806 commented on src/components/toast/Toast.css.ts
> +        zIndex: 1000,
아 임시로 해놓은건데 수정하는걸 깜빡했네요
수정하도록 하겠습니다!

2024-02-24 18:02 UTC, KimGaeun0806 commented on src/utils/toast/ToastProvider.tsx
> +interface PropsType extends PropsWithChildren {}
수정하겠습니다

2024-02-24 18:10 UTC, KimGaeun0806 commented
@RookieAND 
아래 3가지 코멘트에 대해서는 대면으로 이야기한 것처럼 일단 수정하지 않은 채로 두겠습니다.
ToastProvider 사용으로 인한 페이지 전체 리렌더링 현상에 대해서는 추후 같이 이야기해보고 개선해봅시다 ㅜ

2024-02-26 06:26 UTC, KimGaeun0806 commented on src/components/toast/Toast.css.ts
> +const fadeOutAnimation = keyframes({
이후 PR에서 수정하겠습니다!

2024-02-26 06:27 UTC, KimGaeun0806 commented on src/components/toast/Toast.tsx
> +    const { toastMessage, setToast } = useToast();
이 부분은 디자이너분들과 상의한대로 스택으로 쌓이도록 수정하도록 하겠습니다

2024-02-26 06:29 UTC, KimGaeun0806 commented on src/components/toast/Toast.tsx
> +    return (
광인님이 만들어주신 AppPortal을 사용하도록 수정했습니다. 
페이지 전체 리렌더링되는 이슈에 대해서는 넥나잇 때 이야기한 것처럼 일단은 보류하도록 하겠습니다.

2024-02-26 06:34 UTC, RookieAND approved these changes

2024-02-26 06:43 UTC, merged