[AUD-75] 스낵바 공용 컴포넌트 기능 구현
Nexters/audy-client pull request #45
Opened 2024-02-21 22:36 UTC by KimGaeun0806

### 📃 변경사항  
- SnackBarProvider 추가
  - SnackBar의 message, undoFunc를 저장하기 위함
- SnackBar 공용 컴포넌트 구현
  - 5초동안 화면에 보이다가 사라짐
  - 실행취소 버튼을 누를 경우 실행취소되며 스낵바는 바로 사라짐 
- SnackBar를 사용할 수 있는 useSnackBar Hook 구현'
  ```ts
  const { setSnackBar } = useSnackBar();
  setSnackBar({ 
    message: '스낵바', 
    undoFunction: () => { console.log( '실행취소' )}  ,
  });
  ```

### 🫨 고민한 부분
- undoFunction
  - console.log를 찍었을 때 계속 undoFunction이 undefined로 나오고, undoFunction의 실행시기가 이상하던 문제가 있었습니다.
  - 여기서 상당히 시간 허비를 많이 했는데.. useState에 함수를 저장하는 방식이 잘못되어서 그런 거였습니다 ㅜ
  - `[func, setFunc] = useState(() => {})`가 아니라 `[func, setFunc] = useState(() => () => {})` 형식으로 해야한다는걸 몰랐네요...
  - [참고자료](https://stackoverflow.com/questions/55621212/is-it-possible-to-react-usestate-in-react)

- SnackBar 구현 방법 
  - 실행 취소 기능이 있는 SnackBar를 어떻게 구현해야하나 고민을 조금 했는데,
  - 그냥 단순하게 실행 취소 버튼을 눌렀을 때 실행할 함수를 받는 형식으로 하기로 했습니다.
  - 이외에는 Toast와 거의 동일하게 구현했습니다.
  - 솔직히 코드가 썩 맘에 들진 않네요... 더 좋은 의견이 있다면 알려주세요.

### 💫 기타사항 
- 마찬가지로 디자인 확정되면 수정하도록 하겠습니다.

2024-02-22 13:38 UTC, RookieAND requested changes
작업해주셔서 감사합니다.
토스트 UI 와 마찬가지로 염려되는 점이 몇 가지 있어 리뷰를 남겼습니다.

2024-02-22 13:38 UTC, RookieAND commented on src/components/snack-bar/SnackBar.css.ts
> +const fadeOutAnimation = keyframes({
이 부분도 토스트 PR 에서 올린 것과 같이 Framer Motion 구현을 제안드립니다.
컴포넌트가 Unmount 되었을 경우 사라지는 Animation 도 구현할 수 있어서 훨씬 더 자연스러운 UX 를 제공할 수 있어 보입니다.
지금은 onAnimationEnd 로 해결하셨으나 만약 그 전에 undoFunction 이 발동된다면 애니메이션이 중간에 뚝 끊기는 것도 개선해야 할 점이라 생각합니다.

2024-02-22 13:38 UTC, RookieAND commented on src/utils/ui/SnackBarProvider.tsx
> +    const [snackBarUndoFunction, setSnackBarUndoFunction] = useState<
initialState 로 꼭 void 를 반환하는 콜백 함수를 넣어야 할까요?
undoFunction 을 optional 하게 관리하는 게 더 좋지 않을까 생각합니다.

function 이 없더라도 UI 동작에는 문제가 없게끔 하는 방식은 어떤가요?

2024-02-22 13:38 UTC, RookieAND commented on src/main.tsx
> +            <SnackBarProvider>
지금도 토스트 PR 에서 이야기 드렸듯이 여러 개의 Provider 가 (목적은 다르지만 행동이 같은) 계속 감싸지고 있는데 여기에 ModalProvider 까지 만약 추가가 된다면 상당히 구조가 어지러울 것 같습니다.

굳이 여러 개의 Provider 를 사용하지 않고 한 곳에서 모두 처리할 수 있게 하는 방법이 있을까요?
저는 Modal 구현 때 이러한 방식을 개선한 구조를 소개할 예정인데, 내일 이 부분은 PR 올리면서 설명드리겠습니다.

2024-02-22 13:38 UTC, RookieAND commented on src/hooks/useSnackBar.ts
> +        setSnackBarUndoFunction(() => undoFunction);
undoFunction 은 callback 함수이니 이렇게 넘겨도 되지 않을까요?

```ts
setSnackBarUndoFunction(undoFunction);
```

2024-02-22 13:38 UTC, RookieAND commented on src/components/snack-bar/SnackBar.css.ts
> +        zIndex: 1000,
Z-Index 에 대한 Foundation 레벨의 상수 정의도 부탁드립니다.

2024-02-22 13:38 UTC, RookieAND commented on src/components/snack-bar/SnackBar.tsx
> +    const { snackBarMessage, snackBarUndoFunction, setSnackBar } =
여기서는 useContext 로 필요한 값을 모두 꺼내고, useSnackBar 에는 유저가 사용하기 위해 필요한 요소만 넣는 것은 어떤가요?

2024-02-24 18:12 UTC, KimGaeun0806 commented on src/components/snack-bar/SnackBar.css.ts
> +const fadeOutAnimation = keyframes({
아아 실행취소됐을 때에도 애니메이션이 생겨야 하는지 몰랐네요...
디자이너분들께 물어보니 실행취소시에도 자연스럽게 사라지는게 맞다고 하네요
이 부분은 수정하겠습니다
Framer Motion에 대해서는 Toast와 같이 일단은 사용하지 않고 두도록 하겠습니다ㅣ

2024-02-26 06:29 UTC, KimGaeun0806 commented on src/components/snack-bar/SnackBar.css.ts
> +const fadeOutAnimation = keyframes({
가 아니라 다음 PR에서 수정하도록 하겠습니다

2024-02-26 06:34 UTC, RookieAND approved these changes

2024-02-26 07:19 UTC, KimGaeun0806 commented on src/hooks/useSnackBar.ts
> +        setSnackBarUndoFunction(() => undoFunction);
수정하겠습니다

2024-02-26 07:22 UTC, KimGaeun0806 commented
@RookieAND 
이외의 코멘트들에 대해서는
다음 PR에서 구조 수정하면서 반영하도록 하겠습니다

2024-02-26 07:26 UTC, merged