[AUD-9] 시작과 종료 지점 간의 경로 그리기 기능 구현
Nexters/audy-client pull request #8
Opened 2024-01-21 15:49 UTC by RookieAND

### 📃 변경사항  
- 사용자가 선택한 두 마커 간의 경로를 Map 상에서 그리는 메서드 `drawPathBetweenMarkers `구현
- 마커 Class Instance 에서 위경도 값을 추출하는 private 메서드 `extractMarkerPosition `구현
- Tmap Open API 를 활용하기 위한 `TmapRepository `추가 및 경로 요청 API `getRoutePathAsync `구현

### 🫨 고민한 부분 (optional) 
- API 의 경우 토요일에 의논했던 형식인 Repository 패턴을 사용했고, 내부에 쓰이는 type 은 레포와 가깝게 붙였습니다.
- 현재 T Map API 의 경우 경유지가 5개 이상인 경우에 대해서는 지원을 하지 않습니다.
     -  이 부분에 대해서는 API 를 두세번 호출하는 형식으로 갈지가 고민입니다.
     - 예를 들어 1부터 10까지의 경유지가 있다면 1 ~ 7 (경유지 : 2, 3, 4, 5, 6), 8 ~ 10 (경유지 : 9) 로 가는 형식입니다.

### 🎇 동작 화면 (optional)  
![777](https://github.com/Nexters/audy-client/assets/74497253/5dd87925-eed8-47cf-bac5-131e397076bc)

### 💫 기타사항 (optional)  
- 현재 마커 생성 및 삭제 PR 인 AUD-8이 Merge 되지 않은 상황이라 사전에 PR 내용을 가져온 상황입니다.
- 추후 AUD-8 이 Merge 될 경우 AUD-9 도 Merge 되도록 리뷰 부탁드립니다.

2024-01-21 16:52 UTC, RookieAND commented on src/utils/tmap.ts
> +        const handleClickMap = (event: any) => {
마커를 쉽게 생성하기 위해 테스트로 추가한 코드입니다. 리뷰 Approved 후 제거할 예정입니다.

2024-01-22 17:19 UTC, KimGaeun0806 requested changes
고생하셨습니다 !!  🕺🏼
이번엔 가독성적인 측면에서 리뷰를 많이 달게 되었네요...
개인적으로 느끼는 것들에 대해 적은 것이니 선택적으로 반영해주시면 되겠습니다

.　 n_n   n_n   n_n
（(｡･-･)｡･-･)｡･-･))”
ﾟし-Jﾟし-Jﾟし-Jﾟ

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/apis/tmap/type.ts
> +}
타입명 TmapReqParams와 TmapResponses 뒤에 Type을 붙이지 않은 이유가 있으신가요?

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/apis/tmap/index.ts
> +    }: TmapReqParams['getRoutePath']) {
혹시 TmapReqParams.getRoutePath로 쓰지 않고 대괄호표기법으로 사용하는 이유가 있으신가요?
개인적으로는 점 표기법이 더 깔끔하다고 생각하는데, 대괄호표기법이 더 가독성이 낫다고 생각하신건지 궁금합니다!

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
저희 줄임말 쓰지 않기로 했는데 req를 request로 하자고 하면 너무 뇌절인가요 😵‍💫

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +        marker: typeof window.Tmapv3.Marker,
window.Tmapv3를 Tmapv3로 바꾸셔도 될 것 같ㅌ아요

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +        marker: typeof window.Tmapv3.Marker,
아래에 다른 것들도 동일합니다!

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +            const currentEndIndex = i + 6 >= endIndex ? endIndex : i + 6;
개인적으로 이부분 가독성이 조금 떨어진다고 느꼈는데, 숫자들은 상수로 분리하는건 어떨까요?
제가 생각한 느낌을 대충 적어봤는데 
6이라는 숫자만 상수화해도 괜찮을 것 같습니다.
변수명은 대충 지은거니 무시해주셋요

```
const maxPoints = 6;

for (let i = 0; i <= endIndex; i += maxPoints) {
    const isStartPoint = i === 0;
    const currentStartIndex = isStartPoint ? i : i - 1;

    const targetIndex = i + maxPoints;
    const currentEndIndex = targetIndex >= endIndex ? endIndex : targetIndex;
    ...
```

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +                : undefined;
삼항연산자 부분이 너무 길어지는 것 같아서
```
 passMarkers.map((markers) => this.#extractMarkerPosition(markers).join(',')).join('_')
```
부분은 분리해도 좋을 것 같습니다!

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +            });
```
 const path = feature.geometry.coordinates.map(([lng, lat]) => new Tmapv3.LatLng(lat, lng) );
```
```
if (prevFeature && prevFeature.geometry.type === 'Point') {
    const [prevLng, prevLat] =
      prevFeature.geometry.coordinates;
    path.unshift(new Tmapv3.LatLng(prevLat, prevLng));
}
```

위 두 부분은 따로 함수로 분리해서 forEach문 밖으로 빼도 좋을 것 같긴 한데
좀 투머치같기도해서 흘려들으셔도됨더

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +            });
forEach문 안에 너무 많은 로직이 있는 것 같아서 
가독성 측면에서 일부는 함수화 후 forEach 밖으로 빼도 좋을 것 같아서 말씀드렷어여

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +        this.#polylineList.map((polyline) => polyline.setMap(null));
여기서는 forEach를 써도 괜찮을 것 같은데 map을 쓰신 이유가 있으신가요 ?

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/apis/tmap/index.ts
> +    }: TmapReqParams['getRoutePath']) {
이 부분은 논의 후 통일하면 좋을 것 같네요

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +    toggleVisiblePathInMap() {
중요한건 아니지만 `togglePathVisibility`같은 이름도 좋을 것 같네영
`toggleVisiblePathInMap`은 너무 이름이 복잡한 것 같기도 해서..

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +        );
forEach를 써도 좋을 것 같아요

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +    removePathInMap() {
메서드명 뒤에 InMap이 없어도 함수의 역할을 아는 데 큰 문제가 없을 것 같은데 혹시 어떻게 생각하시나요?
InMap을 붙이는게 조금 더 명확하긴 하지만
map 외부에서 경로를 삭제하는 메서드가 생기지는 않을 것 같아서 여쭤봅니더

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +    #extractMarkerPosition(
개취로 extract대신 get이라는 단어가 조금 더 직관적으로 느껴지기는 합니다
그래도 extract가 좀 더 뜻이 명확하긴 해서..  
그냥 제 의견을 제시한 것이니 더 맞다고 생각하신 쪽으로 해주세용

2024-01-22 17:19 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +        }
```
const isStartIndexOutOfRange = startIndex < 0;
const isEndIndexOutOfRange = endIndex >= this.#markers.length;

if (isStartIndexOutOfRange || isEndIndexOutOfRange) return;
```

혹은

```
if (startIndex < 0 ) return;
if (endIndex >= this.#markers.length) return;
```
이렇게 써도 좋을 것 같아요! 개인적으로는 후자의 방법이 조금 더 깔끔한 것 같습니다

2024-01-23 06:29 UTC, RookieAND commented on src/utils/tmap.ts
> +        }
굳이 두개의 조건을 연달아 나열하는 것보다는 OR로 한번에 처리하는 게 더 낫지 않나요?
취향 차이인거 같은데 이 부분에 대한 얼라인을 맞춰야 한다면 논의해볼까요?

2024-01-23 06:30 UTC, RookieAND commented on src/utils/tmap.ts
> +    #extractMarkerPosition(
get, set, has 같은 단어로 목적을 표현하는게 더 맞다고 판단하셨다면 저도 그편이 더 좋아보이네요

2024-01-23 06:30 UTC, RookieAND commented on src/utils/tmap.ts
> +    removePathInMap() {
좋은 의견 감사합니다. 반영해보겠습니다

2024-01-23 06:32 UTC, RookieAND commented on src/apis/tmap/index.ts
> +    }: TmapReqParams['getRoutePath']) {
Type에서는 dot operator 로 하위 속성에 접근이 불가능합니다.
https://www.totaltypescript.com/why-you-cant-use-dot-notation-on-types
여기를 참고하시면 좋습니다

2024-01-23 06:33 UTC, RookieAND commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
사실 이 부분을 풀어쓰면 TmapRequestParamsType 인데..
컨벤션을 지키는 게 좋으니 풀어쓸까요?

2024-01-23 06:34 UTC, RookieAND commented on src/utils/tmap.ts
> +        marker: typeof window.Tmapv3.Marker,
아마 window에서 비구조화 할당을 하시기 전에 작성된 코드여서 그런거 같습니다.
수정해둘게요

2024-01-23 06:35 UTC, RookieAND commented on src/utils/tmap.ts
> +            const currentEndIndex = i + 6 >= endIndex ? endIndex : i + 6;
상수로 분리한다고 해도 결국 삼항 연산자로 조건을 분기처리하는 건 동일해서 크게 의미가 있진 않을거 같습니다. 

게다가 해당 변수를 재활용할 수도 없는터라 일단은 두었습니다. 그렇지만 maxPoints 같은 경우는 상수로 관리하는 게 좋아보이네요

2024-01-23 06:37 UTC, RookieAND commented on src/utils/tmap.ts
> +                : undefined;
저 부분을 그럼 별도의 함수로 치환해서 관리하자는 의견인데, 개인적으로 코드의 분리는 길이보다 내부 로직이 얼마나 많이 뭉쳐있느냐로 구분하는 편입니다.

현재는 함수의 길이가 길어서 코드가 길어보이지만 실제로 로직을 분리한다고 한들 얻는 이점이 더 있을까요?
오히려 관리 포인트가 2개로 늘어서 코드를 추적하기가 더 어려워질 수 있다고 생각합니다. 이에 대한 가은님의 의견이 궁금해요.

2024-01-23 06:39 UTC, RookieAND commented on src/utils/tmap.ts
> +            });
이 부분도 각자의 스타일 차이 같은데 분리의 목적을 어디에 두느냐에 따라서 달라질 수 있다고 생각합니다.
사실 저는 이정도면 크게 지장이 가지 않는다고 생각하는 편이어서요. 분리를 함으로서 얻는 이점이 있을지도 조금 의문이라, 서로 얼라인을 한번 맞추기는 해야겠네요

2024-01-23 06:39 UTC, RookieAND commented on src/utils/tmap.ts
> +        this.#polylineList.map((polyline) => polyline.setMap(null));
map을 쓸 필요가 없어보이네요. 수정하겠습니다

2024-01-23 06:39 UTC, RookieAND commented on src/apis/tmap/type.ts
> +}
제 실수입니다. 수정하겠습니다

2024-01-23 07:12 UTC, KimGaeun0806 commented on src/apis/tmap/index.ts
> +    }: TmapReqParams['getRoutePath']) {
앗 그렇군요 😳 좋은 정보 감사합니다

2024-01-23 07:17 UTC, KimGaeun0806 commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
흠 이 부분도 그냥 편하신대로 해도 좋을 것 같아요
사실 그런식으로 가면 밑에 prev도 풀어써야하고... 변수명의 lat lng도 풀어써야해서...

2024-01-23 07:17 UTC, KimGaeun0806 commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
근데 lat lng는 어떤 곳은 풀어써있고 어떤 곳은 줄여져있어서 이건 통일하면 좋을 것 같아요

2024-01-23 07:17 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +            const currentEndIndex = i + 6 >= endIndex ? endIndex : i + 6;
maxPoints만 상수화해도 좋을 것 같아용

2024-01-23 07:20 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +                : undefined;
한 눈에 봤을 때 눈에 잘 들어오지 않아서 분리하는게 좋다고 생각했습니다.
분리했을 시에 얻는 이점은 가독성일 것 같네요 

개인적으로 map같은 반복문이 들어있는 코드는 분리하는게 좋다고 생각하는 편입니다
이것도 저의 개인적인 취향이니 광인님께서 더 맞다고 생각하는 방향으로 해주셔도 될 것 같아요

2024-01-23 07:26 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +            });
반복문 안에서는 로직을 최대한 간단히 하는게 선언적 프로그래밍에 더 가까워진다고 생각했습니다
이 부분도 개취이니 편하신대로 해주세용

2024-01-23 07:29 UTC, KimGaeun0806 commented on src/utils/tmap.ts
> +        }
이것도 취향 차이인 것 같네요
이정도면 그냥 각자 편한대로 해도 좋을 것 같아요

2024-01-23 07:30 UTC, KimGaeun0806 commented
아직 초반이라 의견을 공유하는게 좋을 것 같아 개인적인 생각을 많이 남겼습니다! 
광인님이 보시기에 굳이싶으신 것들은 수정하지 않으셔도 될 것 같아요

(\____/)
( ͡ ͡° ͜ ʖ ͡ ͡°)
\╭☞ \╭☞

2024-01-23 11:12 UTC, RookieAND commented
덕분에 저도 가독성 좋은 코드에 대해서 더 고민해보는 시간을 가진 것 같습니다.
주신 의견 최대한 반영해서 코드 수정 후 재리뷰 요청 드리도록 할게요.

2024-01-23 11:17 UTC, RookieAND commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
그러면 의미를 함축해도 괜찮은 키워드를 좀 정해볼까요.
lat, lng, prev, req 같은 친구들이 있겠네요.

2024-01-23 11:55 UTC, KimGaeun0806 commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
흠 저는 lat lng정도만 줄여써도 괜찮을 것 같은데 어떻게 생각하시나요?

2024-01-23 11:56 UTC, KimGaeun0806 approved these changes
고생하셨습니다 ! 
줄임표현정도만 같이 논의해보면 괜찮을 것 같네용

2024-01-23 12:06 UTC, merged

2024-01-23 12:08 UTC, RookieAND commented on src/apis/tmap/type.ts
> +export interface TmapReqParams {
lat, lng 정도면 좋아 보이네요