[AUD-21] 검색 API 연동
Nexters/audy-client pull request #9
Opened 2024-01-21 17:14 UTC by KimGaeun0806

### 📃 변경사항  
- 명칭(POI) 상세 정보 검색 AP 연동  
  - 검색어를 파라미터로 넣으면 관련 검색어 10개의 데이터를 반환
- makeQueryString 함수를 utils로 이동

### 🫨 고민한 부분 
- makeQueryString이 들어간 Util 파일 이름 -> 더 좋은 이름이 있으면 코멘트 부탁드립니더
- 검색 시 반환할 데이터 종류
  - 이 부분은 상의 후에 결정하면 좋을 것 같아서 일단은 모두 반환하도록 했습니다.
  - POIType의 경우도  위와 같은 이유로 일단 비워두었습니다.

### 🎇 동작 화면
아래와 같이 반환합니다.
![image](https://github.com/Nexters/audy-client/assets/80266418/9d5ac628-75c5-4e6f-9e97-359e12ff62cc)
![image](https://github.com/Nexters/audy-client/assets/80266418/3962ccb0-43bb-4f88-acb1-59d832bc916b)

### 💫 기타사항 
- 참고자료 (공식문서)
  - https://tmapapi.sktelecom.com/main.html#webservice/docs/tmapPoiDetail
  - https://tmapapi.sktelecom.com/main.html#webservice/sample/WebSamplePoiDetail

2024-01-22 12:23 UTC, RookieAND requested changes
AxiosConfig 를 사용하는 방식으로 코드를 수정하면 더 좋을 것 같습니다!
작업하시느라 고생 많으셨습니다..

2024-01-22 12:23 UTC, RookieAND commented on src/apis/search.ts
> +        const response = await getAsync<GetPOIType>(
getAsync 함수의 두 번째 인자로 AxiosConfig 를 받기 때문에 굳이 param 을 string 으로 변환하지 않아도 아래와 같이 코드를 작성할 수 있습니다.

```ts
async getPOISearchAsync(keyword: string) {
    const response = getAsync<TmapResponses['getPOISearch']>('/tmap/pois', {
        baseURL: `https://apis.openapi.sk.com/tmap`,
        headers: {
            appKey: import.meta.env.VITE_TMAP_APP_KEY,
        },
        params: {
            version: 1,
            format: 'json',
            callback: 'result',
            searchKeyword: keyword,
            resCoordType: 'WGS84GEO',
            reqCoordType: 'WGS84GEO',
            count: 10,
            searchType: 'all',
        }
    });
    return response.searchPoiInfo.pois.poi;
}

```

2024-01-22 12:23 UTC, RookieAND commented on src/utils/queryString.ts
> +export const makeQueryString = (
만약 위의 로직을 그대로 사용한다면 해당 유틸 함수는 굳이 사용하지 않아도 될 거 같습니다.

2024-01-22 17:23 UTC, KimGaeun0806 commented on src/apis/search.ts
> +        const response = await getAsync<GetPOIType>(
그러네용 그렇게 수정하겠습니다 ! 

.  ᕬ ᕬ
(˶ㅇᗜㅇ˶)
(つ🍺⊂)

2024-01-23 11:14 UTC, RookieAND approved these changes
수정해주셔서 감사합니다. LGTM
작업해주신 SearchRepository 는 그때 이야기 드렸듯이 같은 skt api 를 사용하고 있어서 하나의 레포로 묶어서 제가 추후에 반영하도록 할게요.

2024-01-23 11:14 UTC, RookieAND commented on src/pages/LoginPage.tsx
> +import { makeQueryString } from '@/utils/queryString';
해당 유틸은 더 이상 사용하지 않으니 제거해도 될 것 같습니다.

2024-01-23 11:59 UTC, KimGaeun0806 commented on src/pages/LoginPage.tsx
> +import { makeQueryString } from '@/utils/queryString';
제가 실수로 함수를 날려버렸는데 이 페이지에서는 써야하는 것 같습니다.. ㅜ

2024-01-23 12:01 UTC, merged